### PR TITLE
Reading widgets metadata and dealing with units, hidden & tooltip in the UI

### PR DESCRIPTION
**Pull request by YPares**

### CODE REVIEW

**Comment by magnetophon** [comment]
Wow, you really seem to be going for full support of the language! :100: 
Do you think any of your work could be re-used for the regularly compiled [sister project](https://codeberg.org/obsoleszenz/lowpass-lr4-faust-nih-plug)?

**Comment by YPares** [comment]
@magnetophon It could :) Currently, the widgets datatypes are in the `faust_jit` crate, which requires libfaust and hides the faust API (meaning you cannot use it to get the widgets for an already existing dsp C++ pointer, eg. obtained though static compilation of the DSP script), but this could be split further.

Besides that I wanted to converge (as in "factorize some code") with https://github.com/Frando/rust-faust .

**Comment by magnetophon** [comment]
Thanks, that's great to hear!

ping @obsoleszenz

**Comment by YPares** [comment]
But my design choices (compared to rust-faust which is a much more direct wrapper) were a bit different: notably the choice I made to use a higher-level enum to represent faust widgets makes sense when using an immediate mode GUI framework such as egui, it would maybe make less sense with other kind of GUI frameworks.

**Comment by magnetophon** [comment]
How well would those choices fit with [vizia](https://github.com/vizia/vizia)?

**Comment by YPares** [comment]
@magnetophon It would work, for instance by using a new recursive function to transform the hierarchy of DspWidgets into a full-fledged vizia App (but I don't really know vizia). That would be pretty similar to what I do in `faust_jit_egui`. But thus the DspWidgets would then just be treated like a intermediary step.
But that process would happen only once, when loading the DSP, so it doesn't sound that bad and maybe I'm overthinking that.

**Comment by YPares** [comment]
The problem could come from the way I deal with faust zones: they are only accessible in a `SingletonDsp::with_widgets{_mut}` block, to make sure the user doesn't try to make the zones outlive the dsp object itself.

**Comment by magnetophon** [comment]
Thanks!

**Comment by YPares** [comment]
One way could be to change the way zones are exposed to the user: instead of directly exposing mutable references to them, I could provide an opaque "ZoneRef" type (wrapping the zone pointer but not allowing to directly dereference it) and add new `SingletonDsp::{set,get}_zone` methods which could check at runtime that the given ZoneRef is actually inside the dsp, to avoid Segfault-like bugs. But that would require that extra check every time a zone is accessed, and it would be up to the user to make sure they are not calling `{get,set}_zone` with a `ZoneRef` that comes from a different dsp object (whereas in the current situation, `SingletonDsp::with_widgets{_mut}` and Rust lifetimes prevent this from happening).

**Comment by YPares** [comment]
The final concern is that I'm not sure how easy it is to change some widgets in a currently running vizia App. Maybe you need to destroy the App and fully recreate a new one. In my case, egui is nice because I can completely change all my widgets from one frame to the next (when a new DSP is loaded), and it won't complain. Though in an application where the DSP is statically defined that would be much less of a problem.

**Pull request merged**
